### PR TITLE
Update peer dependency to include react 16

### PR DESCRIPTION
**Pull request by chrisdakin**
React 16 is backward compatible. This will remove warnings when packages that depend on this npm install/yarn/etc.

### CODE REVIEW

**Review by dlmr — APPROVED** [review]

**Comment by dlmr** [comment]
Thanks!

**Comment by dlmr** [comment]
Will release this in the morning, ~12 hours.

**Comment by chrisdakin** [comment]
Great, thanks for the quick turnaround!

**Comment by dlmr** [comment]
Released as `1.1.1` 🎉

**Pull request merged**
